### ISSUE TITLE
[Question] 内存不断增长

### ISSUE THREAD

**Issue by magicJie** [jumpserver/magnus-release#1]
**请描述您的问题.**
在CentOS7下按照官方文档安装了最新的 jumpServer，目前还只是出于测试阶段，但是发现/opt/magnus/magnus所在进程使用内存不断增长，为何会出现这个问题，该如何避免？

**Comment by Aaron3S** [comment]
使用 magnus 的场景频繁吗，访问的数据库量大吗，

**Comment by Aaron3S** [comment]
如果您可以复现问题，可以在微信群联系我们处理

**Comment by Aaron3S** [comment]
请检查是否存在tcp探活导致 session 不短增加，7天没有得到回复,暂时关闭

**Comment by magicJie** [comment]
升级到最新版本后此问题没有再出现，谢谢答复
